version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: loan-redis
    ports:
      - "6379:6379"
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    container_name: loan-redisinsight
    ports:
      - "5541:5540"
    depends_on:
      - redis
    restart: always
